version: '2.2'

volumes:
 postgis-data:

services:
 gunicorn_flask:
  #network_mode: "host"
  build: .
  volumes:
  - ./osm:/deploy/app/osm
  - ./ops_settings_docker.yml:/deploy/app/openpoiservice/server/ops_settings.yml
  - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
  ports:
   - "5000:5000"
  mem_limit: 28g
  networks:
   - poi_network

 db:
  image: kartoza/postgis:11.0-2.5
  volumes:
   - postgis-data:/var/lib/postgresql
  environment:
   # If you need to create multiple database you can add coma separated databases eg gis,data
   - POSTGRES_DB=gis
   - POSTGRES_USER=gis_admin
   - POSTGRES_PASS=admin
   - POSTGRES_DBNAME=gis
   - ALLOW_IP_RANGE=0.0.0.0/0
   # Add extensions you need to be enabled by default in the DB. Default are the three specified below
   #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
  ports:
   - 5433:5432
  restart: on-failure
  healthcheck:
   test: "exit 0"
  networks:
   - poi_network

networks:
 poi_network: