version: '3.4'

services:
  gunicorn_flask:
    image: naonedia/expe_logement_openpoiservice
    volumes:
      - ./osm:/deploy/app/osm
      - ./ops_settings_docker.yml:/deploy/app/openpoiservice/server/ops_settings.yml
      - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
    ports:
      - "5000"
    healthcheck:
      test: "curl localhost:5000/pois -X POST -H 'content-type:application/json' -d '{\"request\": \"list\"}' | grep 843"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s

  openpoi_db:
    image: kartoza/postgis:11.0-2.5
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis_admin
      - POSTGRES_PASS=admin
      - POSTGRES_DBNAME=gis
      - ALLOW_IP_RANGE=0.0.0.0/0
