--- 
attribution: "openrouteservice.org | OpenStreetMap contributors"
maximum_categories: 10
# meters
maximum_search_radius_for_linestrings: 2000
maximum_search_radius_for_points: 2000
maximum_search_radius_for_polygons: 2000
# square meters
maximum_area: 50000000
# meters
maximum_linestring_length: 500000
# limit of pois
response_limit: 2000
osm_file_tests: ['pays-de-la-loire-latest.osm.pbf']
concurrent_workers: 1

provider_parameters:
  table_name: ops_planet_pois
  db_name: gis
  user_name: gis_admin
  password: admin
  host: openpoiservice_db_1
  port: 5432
  port_tests: 5432
column_mappings:
  # https://wiki.openstreetmap.org/wiki/Key:name
  name:
  # https://wiki.openstreetmap.org/wiki/Key:wheelchair
  wheelchair:
  # https://wiki.openstreetmap.org/wiki/Key:smoking
  smoking:
  # https://wiki.openstreetmap.org/wiki/Key:fee
  fee:
  # https://wiki.openstreetmap.org/wiki/Key:opening_hours
  opening_hours:
  # https://wiki.openstreetmap.org/wiki/Key:phone
  phone:
  # https://wiki.openstreetmap.org/wiki/Key:website
  website: