version: '3.4'

services:
  api_model_flask:
    image: naonedia/api_model_flask
    ports:
      - "10000:80"
    volumes: 
     - ./newdata/:/data/newdata/
     - ./models/:/data/models/
    healthcheck:
      test: "curl localhost/api/healthcheck | grep OK"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - ENV_TYPE=prod