version: '3.4'

services:
  api_model_flask:
    image: naonedia/expe_logement_api_model:1.0.0b
    ports:
      - "10000:80"
    volumes:
     - ./newdata/:/app/data/newdata/
     - ./models/:/app/data/models/
    healthcheck:
      test: "curl localhost/api/healthcheck | grep OK"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - ENV_TYPE=prod